import base64

cipher = [
    "password",
    "123456789",
    "sunshine",
    "qwerty",
    "iloveyou",
    "princess",
    "admin",
    "welcome",
    "666666",
    "abc123",
    "football",
    "monkey",
    "654321",
    "!@#$%^&*",
    "charlie",
    "aa123456",
    "donald",
    "password1",
    "qwerty123",
    "letmein",
    "zxcvbnm",
    "login",
    "starwars",
    "121212",
    "bailey",
    "freedom",
    "shadow",
    "passw0rd",
    "master",
    "baseball",
    "buster",
    "Daniel",
    "Hannah",
    "Thomas",
    "summer",
    "George",
    "Harley",
    "222222",
    "Jessica",
    "ginger",
    "abcdef",
    "Jordan",
    "55555",
    "Tigger",
    "Joshua",
    "Pepper",
    "Robert",
    "Matthew",
    "Andrew",
    "lakers",
    "andrea",
    "1qaz2wsx",
    "sophie",
    "Ferrari",
    "Cheese",
    "Computer",
    "jesus",
    "Corvette",
    "Mercedes",
    "flower",
    "Blahblah",
    "Maverick",
    "Hello",
    "loveme",
    "nicole",
    "hunter",
    "amanda",
    "jennifer",
    "banana",
    "chelsea",
    "ranger",
    "trustno1",
    "merlin",
    "cookie",
    "ashley",
    "bandit",
    "killer",
    "aaaaaa",
    "1q2w3e",
    "zaq1zaq1",
    "mustang",
    "test",
    "hockey",
    "dallas",
    "whatever",
    "admin123",
    "michael",
    "liverpool",
    "querty",
    "william",
    "soccer",
    "london",
]
array64 = list("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/+=")

base64_strings = ""
with open( "evidence.txt" ) as file:
    listEncoded = file.readlines()

for word in listEncoded:
    base64_strings += array64[ cipher.index(word.replace('\n', '')) ]

result = base64.b64decode(base64_strings).decode('utf-8')
print(result)